# Generated by Django 3.1.5 on 2021-03-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='app',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(default='00001', max_length=15)),
                ('app_name', models.CharField(max_length=50)),
                ('app_copyright', models.CharField(max_length=150)),
                ('app_copyright_href', models.CharField(default='/', max_length=1000)),
                ('app_categary', models.CharField(default='Action Action-Adventure Adventure Simulation Stratergy Stports Puzzle', max_length=100)),
                ('app_sub_categary', models.CharField(default='Windows MAC Android', max_length=100)),
                ('app_description', models.CharField(max_length=37)),
                ('app_maindescription', models.TextField()),
                ('app_version', models.CharField(max_length=30)),
                ('app_license', models.CharField(default='Free', max_length=100)),
                ('app_size', models.CharField(default='000 MB', max_length=50)),
                ('app_pack_name', models.CharField(default='cao.zip', max_length=50)),
                ('app_download_href', models.CharField(default='/', max_length=1000)),
                ('app_release_date', models.DateField()),
                ('app_publish_date', models.DateField()),
                ('appdownloads', models.IntegerField(default=0)),
                ('app_image', models.ImageField(upload_to='download/app/img')),
            ],
        ),
    ]
