# Generated by Django 3.1.5 on 2021-03-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_s', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='appdownloads',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
