# Generated by Django 3.1.5 on 2021-03-09 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_s', '0002_auto_20210309_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='appdownloads',
            new_name='adownloads',
        ),
    ]
