# Generated by Django 3.1.5 on 2021-03-10 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_s', '0003_auto_20210309_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='adownloads',
            new_name='views',
        ),
    ]
