# Generated by Django 3.1.5 on 2021-03-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_s', '0006_auto_20210318_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='app_tags',
            field=models.TextField(default='word,word,word,word,word'),
        ),
        migrations.AlterField(
            model_name='app',
            name='app_categary',
            field=models.CharField(default='Social Communication', max_length=100),
        ),
    ]
