# Generated by Django 3.1.5 on 2021-03-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_s', '0007_auto_20210326_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='app_categary',
            field=models.CharField(default='Social Communication Business Educational Lifestyle Entertainment Travel Utility', max_length=100),
        ),
        migrations.AlterField(
            model_name='app',
            name='app_tags',
            field=models.TextField(default='APP , App , App , app ,  Social , social , Communication , communication , Bussiness , bussiness , Educational , educational , Lifestyle , lifestyle , Travel , Utility , utlity '),
        ),
    ]
