# Generated by Django 3.1.5 on 2021-03-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_s', '0010_auto_20210329_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='app_categary',
            field=models.CharField(default='Social Communication Business Educational Lifestyle Entertainment Travel Utility Tools Multimedia Business Animation 3D-Modeling Development', max_length=100),
        ),
    ]
