# Generated by Django 3.1.5 on 2021-03-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_s', '0011_auto_20210329_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='app_sub_categary',
            field=models.CharField(default='Windows Android', max_length=100),
        ),
    ]
