# Generated by Django 3.1.5 on 2021-03-31 06:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_s', '0012_auto_20210330_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcomments',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appcomments',
            name='ratting',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
