# Generated by Django 3.1.5 on 2021-04-03 06:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_s', '0013_auto_20210331_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='rating',
        ),
        migrations.AddField(
            model_name='app',
            name='ratting',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
