# Generated by Django 3.1.5 on 2021-03-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactrequests',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=150)),
                ('user_subject', models.CharField(max_length=200)),
                ('user_type', models.CharField(max_length=100)),
                ('user_message', models.TextField()),
            ],
        ),
    ]
