# Generated by Django 3.1.5 on 2021-03-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='statustic',
            fields=[
                ('page_id', models.AutoField(primary_key=True, serialize=False)),
                ('page_name', models.CharField(max_length=100)),
                ('page_href', models.CharField(max_length=150)),
                ('page_type', models.CharField(max_length=100)),
                ('page_views', models.IntegerField(default=0)),
            ],
        ),
    ]
