# Generated by Django 3.1.5 on 2021-03-26 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_statustic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='statustic',
        ),
    ]
