# Generated by Django 3.1.5 on 2021-03-26 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_statustic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='statustic',
            new_name='statustics',
        ),
    ]
