# Generated by Django 3.1.5 on 2021-03-26 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210326_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='despAndText',
            fields=[
                ('text_id', models.AutoField(primary_key=True, serialize=False)),
                ('text_name', models.CharField(max_length=120)),
                ('text_tittle', models.CharField(max_length=120)),
                ('text_body', models.TextField(default='hello')),
            ],
        ),
    ]
