# Generated by Django 3.1.5 on 2021-03-28 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_appcomments_gamecomments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamecomments',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gamecomments',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='gamecomments',
            name='user',
        ),
        migrations.DeleteModel(
            name='appcomments',
        ),
        migrations.DeleteModel(
            name='gamecomments',
        ),
    ]
