# Generated by Django 3.1.5 on 2021-03-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210328_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='page_details',
            fields=[
                ('page_id', models.AutoField(primary_key=True, serialize=False)),
                ('page_name', models.CharField(max_length=120)),
                ('page_tittle', models.TextField(default=' " Download name version (Android) - oneup.com " .this tittle will be shown on google search.')),
                ('page_description', models.TextField(default=' Download name version for Android for free , without viruses ... .this will be shown in two line tittle in gooogle search  ')),
                ('page_keywords', models.TextField(default='keywords are like tags in YT or whatever . this will be use in google search engin search the pages ex - oneup , name , download name , download name for android , name for android for free ')),
                ('og_title', models.TextField(default=' "name(subcategory) - oneup.com " .this tittle will be shown when the url will be share on whatsapp or instagram')),
                ('og_description', models.TextField(default='this description will be shown when the url will be share on whatsapp or instagram .max = 20 wrods')),
                ('og_image', models.ImageField(upload_to='main/icon/og')),
            ],
        ),
        migrations.AlterField(
            model_name='despandtext',
            name='text_body',
            field=models.TextField(default='about theat page in the html page but dont make more some have been already made'),
        ),
    ]
