# Generated by Django 3.1.5 on 2021-03-29 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210329_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page_details',
            old_name='og_title',
            new_name='og_tittle',
        ),
    ]
