# Generated by Django 3.1.5 on 2021-03-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(default='00001', max_length=15)),
                ('game_name', models.CharField(max_length=50)),
                ('game_copyright', models.CharField(max_length=150)),
                ('game_copyright_href', models.CharField(default='/', max_length=1000)),
                ('game_categary', models.CharField(default='Action Action-Adventure Adventure Simulation Stratergy Stports Puzzle', max_length=100)),
                ('game_sub_categary', models.CharField(default='Windows MAC Android', max_length=100)),
                ('game_description', models.CharField(max_length=37)),
                ('game_maindescription', models.TextField()),
                ('game_version', models.CharField(max_length=30)),
                ('game_license', models.CharField(default='Free', max_length=100)),
                ('game_size', models.CharField(default='000 MB', max_length=50)),
                ('game_pack_name', models.CharField(default='cao.zip', max_length=50)),
                ('game_download_href', models.CharField(default='/', max_length=1000)),
                ('game_release_date', models.DateField()),
                ('game_publish_date', models.DateField()),
                ('gamedownloads', models.IntegerField(default=0)),
                ('game_image', models.ImageField(upload_to='download/game/img')),
            ],
        ),
    ]
