# Generated by Django 3.1.5 on 2021-03-09 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20210309_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='gamedownloads',
            new_name='gdownloads',
        ),
    ]
