# Generated by Django 3.1.5 on 2021-03-10 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20210309_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='gdownloads',
            new_name='views',
        ),
    ]
