# Generated by Django 3.1.5 on 2021-03-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20210318_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactrequest',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=150)),
                ('user_subject', models.CharField(max_length=200)),
                ('user_type', models.CharField(max_length=100)),
                ('user_message', models.CharField(max_length=10000)),
            ],
        ),
    ]
