# Generated by Django 3.1.5 on 2021-03-23 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_auto_20210323_1452'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactrequest',
        ),
    ]
