# Generated by Django 3.1.5 on 2021-03-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_delete_contactrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_tags',
            field=models.TextField(default='word,word,word,word,word'),
        ),
    ]
