# Generated by Django 3.1.5 on 2021-03-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_game_game_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_tags',
            field=models.TextField(default='Game ,game ,gAME ,Action ,action ,Action-Adventure ,action-adventure ,Adventure ,adventure ,Simulation ,simulation ,Stratergy ,stratergy ,Stports ,stports ,Puzzle ,puzzle'),
        ),
    ]
