# Generated by Django 3.1.5 on 2021-03-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_gamecomments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_copyright',
            new_name='game_author',
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_copyright_href',
        ),
        migrations.AddField(
            model_name='game',
            name='game_author_href',
            field=models.CharField(default='link to go to official web of copyrighter', max_length=1000),
        ),
        migrations.AddField(
            model_name='game',
            name='page_description',
            field=models.TextField(default='above 40 words , bellow 60 Words Download (name) for Android for free, without any viruses, from one up , Try the latest version of (name) for Android . end must contain ...'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_tags',
            field=models.TextField(default='"Download (name) for Android for free, without any viruses, from one up , Try the latest version of (name) for Android , name , category , subcategory , etc "'),
        ),
        migrations.AlterField(
            model_name='gamecomments',
            name='comment',
            field=models.TextField(),
        ),
    ]
