# Generated by Django 3.1.5 on 2021-03-30 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_auto_20210329_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='rating',
        ),
        migrations.AddField(
            model_name='gamecomments',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamecomments',
            name='ratting',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
